"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$directory\
$git_branch\
$git_status\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$docker_context\
$conda\
$time\
$line_break$character
"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
color_fg0 = '#fbf1c7'
color_bg1 = '#3c3836'
color_bg3 = '#665c54'
color_blue = '#458588'
color_aqua = '#689d6a'
color_green = '#98971a'
color_orange = '#d65d0e'
color_purple = '#b16286'
color_red = '#cc241d'
color_yellow = '#d79921'

[os]
disabled = false
style = "fg:color_orange"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""
NixOS = ""

[username]
show_always = true
style_user = "fg:color_orange"
style_root = "fg:color_orange"
format = ' [$user]($style)'

[directory]
style = "fg:color_yellow"
format = " [$path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"

[git_branch]
symbol = ""
style = "fg:color_aqua"
format = ' [$symbol $branch](fg:color_aqua)'

[git_status]
style = "fg:color_aqua"
format = '[($all_status$ahead_behind)](fg:color_aqua)'

[nodejs]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[c]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[rust]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[golang]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[php]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[java]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[kotlin]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[haskell]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[python]
symbol = " "
style = "fg:color_blue"
format = ' [$symbol($version)](fg:color_blue)'

[docker_context]
symbol = " "
style = "fg:color_bg3"
format = ' [$symbol($context)](fg:color_bg3)'

[conda]
style = "fg:color_bg3"
format = ' [$symbol($environment)](fg:color_bg3)'

[time]
disabled = false
time_format = "%R"
style = "fg:color_aqua"
format = ' [ $time](fg:color_aqua)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
